//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueScreen_Simulator.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueScreen_Simulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu :(
        ///Your PC ran into a problem and needs to restart. We&apos;re{endl}just collecting some error info, and then we&apos;ll restart for{endl}you
        ///{p}% complete
        ///For more information about this issue and possible fixes, visit https://windows.com/stopcode
        ///If you call a support person, give them this info:
        ///Stop code: CRITICAL PROCESS DIED
        /////timer settings
        ///1
        ///8
        ///1000
        ///3500
        /////color settings
        ///0
        ///120
        ///215
        ///|141*79#1138*193||141*284#1138*141||141*432#502*38||229*496#1138*38||229*540#1138*18||229*565#1138*156|
        ///
        ///
        /////passw [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QR {
            get {
                object obj = ResourceManager.GetObject("QR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu :DEMO:
        ///{p}         - %                                            {width}       - width of this screen{endl}{pass}    - password                                 {height}      - height of this screen{endl}{cmd}     - command to run 100%           {tmin} {tmax} {cmin} {cmax} - percent step time and count{endl}{scale-x} - scale width on this screen        {unsmode} - is unsafemode checked (settings){endl}{scale-y} - scale height on this screen      {closecmd} - is close after execution checked (settings)
        ///CLI [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string varsdemo {
            get {
                return ResourceManager.GetString("varsdemo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///A problem has been detect and Windows has been shut down to prevent damage to your computer{endl}{endl}{endl}PAGE_FAULT_IN_MONPAGED_AREA{endl}{endl}{endl}If this is the first time you&apos;ve seen this Stop errror screen,{endl}restart your computer. If this screen appears again, follow these steps:{endl}{endl}Check to make sure any new hardware or software is properly installed.{endl}If this is a new instalation, ask your hardware or software manufacturer{endl}for any Windows updates you might need.{endl}{endl [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string win7 {
            get {
                return ResourceManager.GetString("win7", resourceCulture);
            }
        }
    }
}
